-- Table for support tickets
CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_message_id BIGINT NOT NULL,
    admin_message_id BIGINT,
    question_text TEXT NOT NULL,
    reply_text TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'answered')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
    